// <auto-generated>
// Code generated by LUISGen ElectionBot.json -cs Luis.ElectionBot -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class ElectionBot: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            askMood, 
            didNotVote, 
            didVote, 
            discussCoronavirus, 
            discussCrime, 
            discussEducation, 
            discussFeeling, 
            discussHealth, 
            discussHousing, 
            discussLocation, 
            discussMentalHealth, 
            discussMortgage, 
            discussParty, 
            discussTeachersPay, 
            discussUnemployment, 
            endConversation, 
            giveName, 
            giveUserID, 
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] candidate;

            public string[] location;

            public string[] name;

            public string[] party_name;

            public string[] topical_issue;

            public string[] voted;

            // Regex entities
            public string[] userID;

            // Instance
            public class _Instance
            {
                public InstanceData[] candidate;
                public InstanceData[] location;
                public InstanceData[] name;
                public InstanceData[] party_name;
                public InstanceData[] topical_issue;
                public InstanceData[] userID;
                public InstanceData[] voted;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<ElectionBot>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
